const grammarAndTypes = require('./lib/grammar-and-types')
const controlFlowErrorHandling = require('./lib/control-flow-error-handling')
const loops = require('./lib/loops')
const fucntions = require('./lib/functions')
const expressionsAndOperators = require('./lib/expressions-and-operartors')
const numbersAndDates = require('./lib/numbers-and-dates')
const strings = require('./lib/strings')
const indexedCollections = require('./lib/indexed-collections')
const keyedCollections = require('./lib/keyed-collections')

keyedCollections.keyedCollections()